package com.example.temanhijrah.giantplay.Parameter;

public class DataSurah {

    public final String[] surah = {
            "Al-Fatihah",
            "Al-Baqarah",
            "Al-\'Imran",
            "An-Nisa\'",
            "Al-Mai\'dah",
            "Al-An\'am",
            "Al-A\'raf",
            "Al-Anfal",
            "At-Taubah",
            "Yunus",
            "Hud",
            "Yusuf",
            "Ar-Ra\'d",
            "Ibrahim",
            "Al-Hijr",
            "An-Nahl",
            "Al-Isra\'",
            "Al-Kahf",
            "Maryam",
            "Ta Ha",
            "Al-Anbiya",
            "Al-Hajj",
            "Al-Mu\'minun",
            "An-Nur",
            "Al-Furqan",
            "Asy-Syu\'ara\'",
            "An-Naml",
            "Al-Qasas",
            "Al-\'Ankabut",
            "Ar-Rum",
            "Lukman",
            "As-Sajdah",
            "Al-Ahzab",
            "Saba\'",
            "Fatir",
            "Yasin",
            "As-Saffat",
            "Sad",
            "Az-Zumar",
            "Ghafir",
            "Fussilat",
            "Asy-Syura",
            "Az-Zukhruf",
            "Ad-Dukhan",
            "Al-Jasiyah",
            "Al-Ahqaf",
            "Muhammad",
            "Al-Fath",
            "Al-Hujurat",
            "Qaf",
            "Az-Zariyat",
            "At-Tur",
            "An-Najm",
            "Al-Qamar",
            "Ar-Rahman",
            "Al-Waqi\'ah",
            "Al-Hadid",
            "Al-Mujadilah",
            "Al-Hasyr",
            "Al-Mumtahanah",
            "As-Saff",
            "Al-Jumu\'ah",
            "Al-Munafiqun",
            "At-Tagabun",
            "At-Talaq",
            "At-Tahrim",
            "Al-Mulk",
            "Al-Qalam",
            "Al-Haqqah",
            "Al-Ma'arij",
            "Nuh",
            "Al-Jinn",
            "Al-Muzzammil",
            "Al-Muddassir",
            "Al-Qiyamah",
            "Al-Insan",
            "Al-Mursalat",
            "An-Naba\'",
            "An-Nazi\'at",
            "\'Abasa",
            "At-Takwir",
            "Al-Infitar",
            "Al-Tatfif",
            "Al-Insyiqaq",
            "Al-Buruj",
            "At-Tariq",
            "Al-A\'la",
            "Al-Gasyiyah",
            "Al-Fajr",
            "Al-Balad",
            "Asy-Syams",
            "Al-Lail",
            "Ad-Duha",
            "Al-Insyirah",
            "At-Tin",
            "Al-\'Alaq",
            "Al-Qadr",
            "Al-Bayyinah",
            "Az-Zalzalah",
            "Al-\'Adiyat",
            "Al-Qari\'ah",
            "At-Takasur",
            "Al-\'Asr",
            "Al-Humazah",
            "Al-Fil",
            "Quraisy",
            "Al-Ma\'un",
            "Al-Kausar",
            "Al-Kafirun",
            "An-Nasr",
            "Al-Lahab",
            "Al-Ikhlas",
            "Al-Falaq",
            "An-Nas",
    };

    public final String[] translate = {
            "Pembukaan",
            "Sapi Betina",
            "Keluarga \'Imran",
            "Wanita",
            "Jamuan (Hidangan Makanan)",
            "Hewan Ternak",
            "Tempat yang Tertinggi",
            "Harta Rampasan Perang",
            "Pengampunan",
            "Nabi Yunus",
            "Nabi Hud",
            "Nabi Yusuf",
            "Guruh (Petir)",
            "Nabi Ibrahim",
            "Gunung Al Hijr",
            "Lebah",
            "Perjalanan Malam",
            "Penghuni-penghuni Gua",
            "Maryam",
            "Ta Ha",
            "Nabi-nabi",
            "Haji",
            "Orang-orang Mukmin",
            "Cahaya",
            "Pembeda",
            "Penyair",
            "Semut",
            "Kisah",
            "Laba-laba",
            "Bangsa Romawi",
            "Keluarga Luqman",
            "Sajdah",
            "Golongan-golongan yang Bersekutu",
            "Kaum Saba\'",
            "Pencipta",
            "Yaasiin",
            "Barisan-barisan",
            "Shaad",
            "Rombongan-rombongan",
            "Yang Mengampuni",
            "Yang Dijelaskan",
            "Musyawarah",
            "Perhiasan",
            "Kabut",
            "Yang Bertekuk Lutut",
            "Bukit-bukit pasir",
            "Nabi Muhammad",
            "Kemenangan",
            "Kamar-kamar",
            "Qaaf",
            "Angin yang Menerbangkan",
            "Bukit",
            "Bintang",
            "Bulan",
            "Yang Maha Pemurah",
            "Hari Kiamat",
            "Besi",
            "Wanita yang Mengajukan Gugatan",
            "Pengusiran",
            "Wanita yang Diuji",
            "Satu Barisan",
            "Hari Jum\'at",
            "Orang-orang yang Munafik",
            "Hari Dinampakkan Kesalahan-kesalahan",
            "Talak",
            "Mengharamkan",
            "Kerajaan",
            "Pena",
            "Hari Kiamat",
            "Tempat Naik",
            "Nabi Buh",
            "Jin",
            "Orang yang Berselimut",
            "Orang yang Berkemul",
            "Kiamat",
            "Manusia",
            "Malaikat-malaikat yang Diutus",
            "Berita Besar",
            "Malaikat-malaikat yang Mencabut",
            "Ia Bermuka Masam",
            "Menggulung",
            "Terbelah",
            "Orang-orang yang Curang",
            "Terbelah",
            "Gugusan Bintang",
            "Yang Datang di Malam Hari",
            "Yang Paling Tinggi",
            "Hari Pembalasan",
            "Fajar",
            "Negeri",
            "Matahari",
            "Malam",
            "Waktu Dhuha",
            "Melapangkan",
            "Buah Tin",
            "Segumpal Darah",
            "Kemuliaan",
            "Pembuktian",
            "Kegoncangan",
            "Berlari Kencang",
            "Hari Kiamat",
            "Bermegah-megahan",
            "Masa/Waktu",
            "Pengumpat",
            "Gajah",
            "Suku Quraisy",
            "Barang-barang yang Berguna",
            "Nikmat yang Berlimpah",
            "Orang-orang Kafir",
            "Pertolongan",
            "Gejolak Api",
            "Ikhlas",
            "Waktu Subuh",
            "Umat Manusia",
    };

    public DataSurah() {
    }
}
